//TODO: CHECK FOR FALLBACKS
using ImageGen.Domain.Entities;

namespace ImageGen.Application.Rendering;

/// <summary>What a job or slot is doing, as reported to a client.</summary>
public enum RenderPhase
{
    /// <summary>Waiting — and NOT on the GPU. Covers a slot the scheduler hasn't reached, one the worker has picked
    /// and is preparing, and one already handed to the backend but not executing yet.</summary>
    Queued,
    /// <summary>Being generated by the GPU right now.</summary>
    Running,
    /// <summary>Finished; an image exists (or an edit intentionally declined).</summary>
    Done,
    /// <summary>Failed: something went wrong.</summary>
    Error,
    /// <summary>Stopped because the user asked. Not a failure, and not styled as one.</summary>
    Cancelled,
}

/// <summary>
/// The ONE derivation of a render phase, for every caller.
///
/// <para>It exists because "running" was decided independently in four view builders and three of them meant something
/// weaker than "on the GPU": a batch that had merely started (one finished slot, the rest waiting), an Active database
/// row (any non-terminal job, including ones no live worker owned), and a slot the scheduler had picked but not yet
/// submitted. On a single-GPU box that read back as dozens of jobs "running" at once while nothing was generating.</para>
///
/// <para>The rule that replaces them: <b>running is a live fact about a GPU</b>. It is entered only on the backend's
/// report that the prompt is executing (<see cref="SlotState.Running"/>), it lives only in the owning instance's
/// memory, and it is never inferred from anything else — least of all from a durable row, which is a claim from some
/// earlier moment with no GPU behind it any more.</para>
/// </summary>
public static class RenderPhases
{
    /// <summary>
    /// A LIVE job's phase — the in-memory working set of the instance that owns it.
    /// <para>Cancelled is tested before Done: a batch of ten stopped after three images landed ended because the user
    /// stopped it, so "cancelled · 3/10" is what happened, where "done · 3/10" claims it ran its course. A slot that
    /// merely failed does not get that precedence — a partial failure has always read as done-with-fewer.</para>
    /// </summary>
    public static RenderPhase Of(RenderJob job) =>
        job.IsRendering ? RenderPhase.Running
        : !job.AllTerminal ? RenderPhase.Queued
        : job.Slots.Exists(s => s.State == SlotState.Cancelled) ? RenderPhase.Cancelled
        : job.Produced > 0 ? RenderPhase.Done
        : RenderPhase.Error;

    /// <summary>A live slot's phase.</summary>
    public static RenderPhase Of(SlotState state) => state switch
    {
        SlotState.Running => RenderPhase.Running,
        SlotState.Done => RenderPhase.Done,
        SlotState.Error => RenderPhase.Error,
        SlotState.Cancelled => RenderPhase.Cancelled,
        _ => RenderPhase.Queued,
    };

    /// <summary>
    /// A DURABLE job record's phase. Never <see cref="RenderPhase.Running"/>: a record is read precisely when the job
    /// is not in its owning instance's live set, so whatever it once claimed, nothing is executing it now. A
    /// non-terminal row reads as queued — including a stranded one, which is waiting for a worker that may never come
    /// but is still not on a GPU.
    /// </summary>
    public static RenderPhase Of(JobStatus status) => status switch
    {
        JobStatus.Done => RenderPhase.Done,
        JobStatus.Error => RenderPhase.Error,
        JobStatus.Cancelled => RenderPhase.Cancelled,
        _ => RenderPhase.Queued,
    };

    /// <summary>A durable slot record's phase. <see cref="JobSlotState.Running"/> is legacy — rows written before
    /// running became live-only still hold it — and reads as queued for the same reason.</summary>
    public static RenderPhase Of(JobSlotState state) => state switch
    {
        JobSlotState.Done => RenderPhase.Done,
        JobSlotState.Error => RenderPhase.Error,
        JobSlotState.Cancelled => RenderPhase.Cancelled,
        _ => RenderPhase.Queued,
    };

    /// <summary>
    /// The durable spelling of a live slot state. A running slot persists as <see cref="JobSlotState.Queued"/>: the
    /// row cannot keep "on the GPU" true past this process's life, and writing it anyway is what left crashed and
    /// orphaned rows claiming to render forever. Everything resuming actually needs is stored beside it — the slot is
    /// non-terminal and carries its <c>ComfyPromptId</c>.
    /// </summary>
    public static JobSlotState Persisted(SlotState state) => state switch
    {
        SlotState.Done => JobSlotState.Done,
        SlotState.Error => JobSlotState.Error,
        SlotState.Cancelled => JobSlotState.Cancelled,
        _ => JobSlotState.Queued,
    };

    /// <summary>The durable spelling of a live job's status, derived from the SAME rule the client's phase comes from
    /// so the row and the page can't tell different stories about how a job ended.</summary>
    public static JobStatus Persisted(RenderJob job) => !job.AllTerminal ? JobStatus.Active : Of(job) switch
    {
        RenderPhase.Done => JobStatus.Done,
        RenderPhase.Cancelled => JobStatus.Cancelled,
        _ => JobStatus.Error,
    };

    /// <summary>The live spelling of a durable slot state — what a rehydrated slot comes back as.</summary>
    public static SlotState Live(JobSlotState state) => state switch
    {
        JobSlotState.Done => SlotState.Done,
        JobSlotState.Error => SlotState.Error,
        JobSlotState.Cancelled => SlotState.Cancelled,
        // Non-terminal comes back Queued — including a legacy Running row, which no GPU has been holding since
        // whenever the writing instance last stopped. It becomes Running again only if the backend says it's executing.
        _ => SlotState.Queued,
    };

    /// <summary>The wire spelling of a phase.</summary>
    public static string Wire(this RenderPhase phase) => phase switch
    {
        RenderPhase.Running => "running",
        RenderPhase.Done => "done",
        RenderPhase.Error => "error",
        RenderPhase.Cancelled => "cancelled",
        _ => "queued",
    };
}
